default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: nikitakroshko
  host: localhost

development:
  <<: *default
  database: ruby_blog_development

test:
  <<: *default
  database: ruby_blog_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %> # OK for Heroku (leave it)

  cache:
    <<: *default
    database: ruby_blog_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: ruby_blog_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: ruby_blog_production_cable
    migrations_paths: db/cable_migrate
